version: '3'

services:
  api:
    build: .
    ports:
      - "5000:8000"
    volumes:
      - .:/app
    environment:
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
      - SELENIUM_HEADLESS=1
      - CHROME_BIN=/usr/bin/chromium
      - CHROMIUM_PATH=/usr/bin/chromium
      - CHROMEDRIVER_PATH=/usr/bin/chromedriver
      - PYTHONDONTWRITEBYTECODE=1
      - LOG_LEVEL=INFO
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s 