name: Deploy to Azure Container Apps

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY_NAME: taurusapiregistry
  APP_NAME: taurus-transit-api
  RESOURCE_GROUP: taurus-api-rg
  PYTHON_VERSION: "3.10"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Build Docker image
      run: |
        docker build -t taurusapiregistry.azurecr.io/taurus-transit-api:latest .
      
    - name: Login to ACR with admin credentials
      run: |
        docker login taurusapiregistry.azurecr.io -u taurusapiregistry -p ${{ secrets.ACR_PASSWORD }}
      
    - name: Push Docker image to ACR
      run: |
        docker push taurusapiregistry.azurecr.io/taurus-transit-api:latest
      
    - name: Deploy to Azure Container App
      run: |
        az containerapp update \
          --name taurus-transit-api \
          --resource-group taurus-api-rg \
          --image taurusapiregistry.azurecr.io/taurus-transit-api:latest
      
    - name: Get Container App URL
      run: |
        echo "Deployment successful! Your API is available at: https://$(az containerapp show --name taurus-transit-api --resource-group taurus-api-rg --query properties.configuration.ingress.fqdn -o tsv)" 